### ISSUE TITLE
Update AppSettings through Shopify API

### ISSUE THREAD

**Issue by aimproxy** [carstenlebek/shopify-non-embedded-app-template#6]
Why LocalTunnel instead of Ngrok? And how can we update AppSettings through Shopify API? If that is possible... Shopify makes it really painful to change it every time with ngrok always changing URL's all the time.

**Comment by carstenlebek** [comment]
The reason for using localtunnel is, that it's a non commercial open source alternative to ngrok. You can set a fixed subdomain without paying for a subscription. 

If you follow the getting started steps of the Readme, you'll only have to set the urls in the app settings once, as the app url will be fixed to your set subdomain.

I haven't found a way to update the app settings via the API for now. Maybe it's possible to find a way by reading the code of the shopify CLI. PRs are welcome.

**Comment by aimproxy** [comment]
@carstenlebek I did found a way to update App URL's trought their GraphQL API. I found this:

[update_dashboard_urls.graphql](https://github.com/Shopify/shopify-cli/blob/main/lib/graphql/update_dashboard_urls.graphql)

This opertion can be performed through Partners API, as demonstrated on Shopify CLI repo:
```rb
 ShopifyCli::Helpers::PartnersAPI.query(@ctx, 'update_dashboard_urls', input: {
            redirectUrlWhitelist: with_loopback, apiKey: api_key
})
```
But I doubt that we have the required scopes to do it! I will investigate it further and If I find any solution I will be pleased to submit a pull request to your repo! 

Here the Pull Request that made this possible: 
[Adds check for custom application urls and prompts user to update](https://github.com/Shopify/shopify-cli/commit/a1604d5ba569e762408bf3ea53609e8508ed9120)

**Comment by carstenlebek** [comment]
Sounds great! Maybe it's possible to reverse engineer the authentication process of the shopify CLI.

**Comment by aimproxy** [comment]
Digging a little bit, I do think this is the way in!

![Screenshot 2022-06-20 at 18-52-08 Shopify Partners](https://user-images.githubusercontent.com/47716563/174655989-0ee34983-43e5-4b92-9c01-3182c5fd98a5.png)

**Comment by aimproxy** [comment]
Last night, localtunnel was down and the opportunity was presented again to test Ngrok, as knowned there is no endpoint opened to the public to update the app redirect URLs... But with the appearance of Shopify CLI, I was able to migrate my NextJs project to work with Shopify CLI 3 and it worked fine. Now my app uses the Ngrok Tunnel and Updates the Shopify Callback URLs, but I have to fetch the Ngrok API Endpoint to get the last tunnel URL and write it into the environment. That is what, it took to put it together... I found that Shopify makes it more accessible now to develop apps...

In beef of this issue, there is an option on Shopify Cli to not update the redirect URLs, but there isn't one to add custom redirect URLs, that would be a nice addition if the Shopify team would be open to doing it! As for localtunnel it's still down today and I think maybe it will not come up again very soon! Maybe is dead? Maybe is not! It's just that it was a strike for me last night!

And perhaps you could explain to me a thing, why does the offline callback URL redirect the browser again to the auth URL, forcing it to go through a loop... Are there different steps in installation? Couldn't offline callback redirect directly to the app and the middleware will catch it?

Thanks again for your incredible work, it really helped me to get started with Shopify!

**Comment by carstenlebek** [comment]
Localtunnel sadly has proven, that it isn't a reliable solution.

I think the easiest way for now will be to make the template work with the Shopify CLI. I will try to find a working solution.

The template gets the offline and online tokens. The app has to go through the oauth flow for both tokens. As not everybody needs both tokens, I will make the offline token optional.

No Problem, great to hear!

**Comment by aimproxy** [comment]
I have exactly that problem! If you just explain to me how I can just ensure that I have a valid permanent token, I will be pleased! Do I really need to get an online token every time `_middleware.ts` is called? Because I just need an offline token!

**Comment by aimproxy** [comment]
Never mind I just did it!

**Comment by carstenlebek** [comment]
@aimproxy I have found a way to update the App URLs via the api. I will be publishing it later today.

Localtunnel is still down, so the template will switch to Ngrok permanently.

**Comment by aimproxy** [comment]
@carstenlebek That's awesome! That way I can customise the endpoint :+1: What exactly did you find? Reverse engineering on Shopify CLI or did they update their API docs?

Thank you for giving your attention and efforts to this repo! :100: 
I will tell some friends to star your repo!

**Comment by carstenlebek** [comment]
@aimproxy I've read through the code of the Shopify CLI and found that it is possible to use the [@shopify/cli-kit](https://www.npmjs.com/package/@shopify/cli-kit) package to authenticate a partner account and access the API responsible for creating and editing apps and shops. From there it was pretty easy to implement a solution. The authentication is the same as in the official Shopify CLI and the app and shop are set in the environment variables.

Thanks! I'm always happy to help 😃
